### ISSUE TITLE
Is it possible to hide the reels tab or icon on the Instagram?

### ISSUE THREAD

**Issue by zeuikli** [SoCuul/BHInsta#14]
Could you clarify if this commit hides the reels icon or tab on the main view?

https://github.com/vlourme/BHInsta/commit/9b71600f8edc32afa9316886e8fbb15d6ef5d931

**Comment by zeuikli** [comment]
It has already been included by a PR.
https://github.com/SoCuul/BHInsta/pull/8

**Comment by SoCuul** [comment]
Hey! I'm currently on vacation right now so I can't work on updating this pr, but I'll try to implement it in the next month.

**Comment by vlourme** [comment]
@SoCuul I was a little busy, but the PR is now updated with what you asked for.

**Comment by SoCuul** [comment]
> @SoCuul I was a little busy, but the PR is now updated with what you asked for.

Thanks! I'll try to merge it in the next little bit.

**Comment by zeuikli** [comment]
Will GitHub workflow be used to build the IPA with your latest commit?

Ref: https://github.com/arichornlover/uYouEnhanced/tree/main/.github

**Comment by SoCuul** [comment]
As of right now I can't confirm if I will implement the GitHub actions building workflow by the release.
If anyone could draft a pr introducing it, I'd be glad to review it when I have the time!

**Comment by SoCuul** [comment]
Implemented in bea23eb
