### ISSUE TITLE
Deb tweak

### ISSUE THREAD

**Issue by fetchhh** [SoCuul/BHInsta#17]
Hello, is it possible to upload the tweak as a rootless deb?

**Comment by vlourme** [comment]
It's meant to be sideloaded, so it's already rootless.
You can clone and run `make do`. You should get a `.deb` in the `packages` directory.

However, this is not a tested way of using this project, we've been working only on making an `ipa` file at the end.
I'd be interested to know if it works correctly when used this way. Also, `libbhflex` dependency is not listed in the `control` file, installation might not work as expected. Be sure to build a `deb` file also for the libbhflex.

**Comment by SoCuul** [comment]
As @vlourme the only supported installation method currently is IPA, as it works for all pretty much all use-cases. Also, I am unable to test the tweak on a jailbroken device, so it's not worth it to me to try supporting it.

**Comment by SoCuul** [comment]
I'm going to mark this issue as closed for now, but if there's any reason why a deb could provide functionality that an IPA couldn't, I'll be more than happy to reopen it 😁
