### ISSUE TITLE
Sideloading

### ISSUE THREAD

**Issue by Invisible40** [SoCuul/BHInsta#2]
Not too familiar with sideloading nowadays - how can I add this IPA? Or, is it not complete yet?

**Comment by vlourme** [comment]
Hi, you can find a built IPA file on my own fork which is very similar to this one. I don't know if @SoCuul plans to build and release IPA on his repository, as it could be taken down by DMCA (seems pretty rare, though).

Else, you can build it yourself using a decrypted IPA file (can be found on ipaarchive.com). The building script in this repository is not working for me, you can find a working `build.sh` on my fork. It should work with this repository code as well.

Last thing, I personally use Sideloadly (for dev/testing) or MapleSign (for long-term usage on my phone and Push Notifications), but it should work with any other IPA installer and signer.

**Comment by SoCuul** [comment]
@Invisible40 With the latest version just published, building the IPA for yourself should be much more straightforward. If you need any help, let me know!
