### ISSUE TITLE
Couldn't find libbhFLEX.dylib

### ISSUE THREAD

**Issue by jobsgonnawork** [SoCuul/BHInsta#20]
![Screenshot 2024-04-05 at 18 10 32](https://github.com/SoCuul/BHInsta/assets/65244672/be8d2b44-921d-40d0-b45b-e196bda44cab)

**Comment by SoCuul** [comment]
Did you make sure to clone the repo with `--recurse-submodules`?
Check the modules/libflex/FLEX directory and make sure it's not empty.

**Comment by cranci1** [comment]
Same issue here:
![Screenshot 2024-04-09 at 14 23 19](https://github.com/SoCuul/BHInsta/assets/100066266/09a56f32-8bc0-45fa-8271-08a20d7ea983)

**Comment by SoCuul** [comment]
> Same issue here: (i did clone using --recurse-submodules) ![Screenshot 2024-04-09 at 14 23 19](https://private-user-images.githubusercontent.com/100066266/320862026-09a56f32-8bc0-45fa-8271-08a20d7ea983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2ODg1MTUsIm5iZiI6MTcxMjY4ODIxNSwicGF0aCI6Ii8xMDAwNjYyNjYvMzIwODYyMDI2LTA5YTU2ZjMyLThiYzAtNDVmYS04MjcxLTA4YTIwZDdlYTk4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxODQzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTc3ZmU2ODZkZmVkYmEwN2ZiYjY0MDJlNWZkMGNmNmY5NzEwYWFmYTU5MjVlODdhYTRiYzQzNTA1OWM3MmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2Y5jSGuxZWpi4rnIq9WitTctVii1wT9KPcwKm4pnFXU)

Could you check the ./modules/libflex/FLEX directory and make sure it's not empty.

**Comment by cranci1** [comment]
The /modules/libflex/FLEX directory is not empty

![Screenshot 2024-04-10 at 13 26 41](https://github.com/SoCuul/BHInsta/assets/100066266/f7d520b1-b9c7-42ad-bd85-fa448fcb6565)

**Comment by SoCuul** [comment]
Which version of macOS, Xcode build tools, theos and gnu make are you running?

If you could run these commands and post the results that'd be great.
```sh
xcode-select --version
cd $THEOS && git rev-parse --short HEAD
make --version
```

**Comment by cranci1** [comment]
Here you go 

Xcode build tools = 2384
Theos = a55932f
GNU = 3.81

![Screenshot 2024-04-11 at 07 06 04](https://github.com/SoCuul/BHInsta/assets/100066266/640518dd-500a-4aeb-8e5d-1a6242da41be)

**Comment by SoCuul** [comment]
Looks like your mac is using GNU make provided by macOS (which hasn't been updated since 2006 because of copyright things).

This article covers how to switch to a newer version of make: https://theos.dev/docs/parallel-building

Essentially:
```sh
brew install make
echo PATH=\"$(brew --prefix make)/libexec/gnubin:\$PATH\" >> ~/.zprofile
```

Try this out and attempt to build it again. Feel free to tell me how it goes, so I can update the documentation if this is what fixes it!

**Comment by cranci1** [comment]
Alright, I've managed to resolve the issue with compiling libFLEX. It turned out that there were errors stemming from conflicting SDK versions—specifically, I had SDK 17.4 conflicting with 16.1. Removing these conflicting SDKs allowed libFLEX to compile perfectly, even with an older GNU version.

**Comment by SoCuul** [comment]
Glad it worked out in the end!

@jobsgonnawork try removing any conflicting sdks to see if that fixes your problem as well!

**Comment by cranci1** [comment]
Yeah just remove all the sdks (temporarily you can re add them layer) from ios 16.0-17.4 this should fix

**Comment by noxwell** [comment]
I had the same problem and I don't see `libflex` make invocation in `build.sh`. I had to do this:
```
cd modules/libflex
make
```
before `./build.sh` to make it work. For developer: probably you would need to test `build.sh` on clean `git clone` and fix build scripts.

**Comment by asdfzxcvbn** [comment]
> I had the same problem and I don't see `libflex` make invocation in `build.sh`. I had to do this:
> 
> ```
> cd modules/libflex
> make
> ```
> 
> before `./build.sh` to make it work. For developer: probably you would need to test `build.sh` on clean `git clone` and fix build scripts.

exactly what i mentioned in [my PR](https://github.com/SoCuul/BHInsta/pull/24). `SUBPROJECTS` is being used incorrectly, i don't know how it would work without doing those steps.
