### ISSUE TITLE
QoL improvements

### ISSUE THREAD

**Issue by k3v1nwrld** [SoCuul/BHInsta#21]
Could you use [Pyzule](https://github.com/asdfzxcvbn/pyzule) instead of Azule, as it is not maintained anymore and pyzule is just better overall. Also, it would be nice if downloaded images/videos would be removed from the documents folder as they take up unnecessary space (on app startup or after downloading them). Thanks

**Comment by SoCuul** [comment]
Hey!

What are the main benefits of switching over to Pyzule?

**Comment by k3v1nwrld** [comment]
Faster, has like no bugs at all and is a frequently updated project. Azule has not gotten actual fixes to the bugs it has in a little over a year. On linux for example, if you do anything that involves the use of LDID, the app wont install

**Comment by SoCuul** [comment]
> Faster, has like no bugs at all and is a frequently updated project. Azule has not gotten actual fixes to the bugs it has in a little over a year. On linux for example, if you do anything that involves the use of LDID, the app wont install

Could you possibly put together a pull request to migrate to Pyzule? I don't currently have the time to implement it and find out the differences between it and Azule.

**Comment by SoCuul** [comment]
@asdfzxcvbn Just noticed that you're the dev of pyzule. Does it work as a drop-in replacement or are there noticeable differences?

**Comment by asdfzxcvbn** [comment]
> @asdfzxcvbn Just noticed that you're the dev of pyzule. Does it work as a drop-in replacement or are there noticeable differences?

while the repo says it's a "clone", it really isnt an exact clone. so some flags are different, for example, your script uses:

https://github.com/SoCuul/BHInsta/blob/3dea058a31f36e3c4bcf1895aa759250e00f64ae/build.sh#L18

in pyzule, this would be done like so:

`pyzule -i "$PROJECT_PATH/packages/${ipaFile}" -o "$PROJECT_PATH/packages/BHInsta-sideloaded" -f "$PROJECT_PATH/.theos/obj/debug/BHInsta.dylib" "$PROJECT_PATH/modules/libflex/.theos/obj/debug/libbhFLEX.dylib`

also, i generally recommend using more flags and not only `-f`, so i would recommend this:

`pyzule -i "$PROJECT_PATH/packages/${ipaFile}" -o "$PROJECT_PATH/packages/BHInsta-sideloaded" -uwsgf "$PROJECT_PATH/.theos/obj/debug/BHInsta.dylib" "$PROJECT_PATH/modules/libflex/.theos/obj/debug/libbhFLEX.dylib -m 15.0`

this removes UISupportedDevices, removes any watch apps, fakesigns the app, removes encrypted app extensions, and sets the minimum os version to v15.0 (required by the latest versions of instagram). you could also replace `-g` with `-e` to completely remove all app extensions, which might be helpful for users who aren't using paid certs to install the ipa.

cephei, substrate, and pretty much any other dependencies will be automatically injected. so you could remove those from the repo if you'd like.

**Comment by SoCuul** [comment]
Hey, thanks for the in-depth response! Is there any chance you could possibly make a pull request with azule swapped out in favour of pyzule? I don't currently have time to test it out.

**Comment by asdfzxcvbn** [comment]
sure, i'll be free in a bit

**Comment by SoCuul** [comment]
As of the most recent commits the project has fully switched over to using Pyzule.

For the deleting files part, right now you can remove them via FLEX, and new built IPAs should have files access enabled.
I could possibly see an implementation to delete the file after the share menu is closed, but I'm not sure.
